# Sitenizin adını ve açıklamasını belirleyin.
site_name: Eva AI Help
site_description: Eva AI Help

# Sitenizin temasını ve rengini seçin.
theme:
  name: material
  palette:
    primary: deep purple
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

# Navigasyon (menü) yapınızı oluşturun.
# Sayfalarınızın sırasını ve hiyerarşisini burada düzenleyebilirsiniz.
nav:
  - Welcome:
    - 'Main Page': 'index.md'
    - 'Why Eva': 'why-eva.md'
  - 'Getting Started':
    - 'Creating Your Eva Account': 'getting-started/creating-your-eva-account.md'  
    - 'Connecting Your Amazon Store': 'getting-started/connecting-your-amazon-store.md'
    - 'Connecting Your Ad Account': 'getting-started/connecting-your-ad-account.md'
  - 'Performance & Goal Setting':
    - 'Trend Analytics': # Bu başlık bir alt bölüm haline getirildi.
        - 'Overview': 'performance-analysis-setting-goals/trend-analytics.md'
        - 'Dynamic Chart': 'performance-analysis-setting-goals/dynamic-chart.md'
        - 'Interactive Table': 'performance-analysis-setting-goals/products.md'
        - 'Custom Product Tagging': 'performance-analysis-setting-goals/custom-tagging.md'
        - 'Advanced Product Filtering': 'performance-analysis-setting-goals/product-filtering.md' # 'Advenced' yazım hatası düzeltildi.
    - 'Product Details': 'performance-analysis-setting-goals/trend-analytics-product-details.md' # Doğru başlık altına taşındı.
    - 'Metrics': 'performance-analysis-setting-goals/metrics.md' # Doğru başlık altına taşındı.
  - 'Ad Strategies':
    - 'Setting Store-Level Goals': 'ad-strategies/store-level-goals.md'
    - 'Setting Product-Level Goals': 'ad-strategies/product-level-goals.md'
    - 'Campaign-Level Goals': 'ad-strategies/campaign-level-goals.md'
  - 'In-Depth Views':
    - 'Campaign View': 'in-depth-views/campaign-view.md'
    - 'Target View': 'in-depth-views/target-view.md'
  - Reports:
    - 'Performance Trends Report': 'reports/performance-trends-report.md'
    - 'File-Based Reports': 'reports/file-based-reports.md'
    - 'Audit Report': 'reports/audit-report.md'
    - 'AI Decisions': 'reports/ai-decisions.md'
  - 'Subscription Management':
    - 'Managing Your Plan': 'scaleads-subscription/managing-your-plan.md'
    - 'Dedicated Support': 'scaleads-subscription/dedicated-support.md'

# Ekstralar ve eklentiler.
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight